name: Yuri's Resume CI/CD
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install packages
        run: npm install
      - name: Run tests
        run: npm test
        env:
          CI: true
      - name: Build production version
        run: npm run build
      - name: Store results of build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Load results of build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Upload to server
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          privateKey: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.REMOTE_USER }}
          remote: build
          local: build
      - name: Perform deployment and clean up
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          privateKey: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.REMOTE_USER }}
          command: rm -rf ./${{ secrets.REMOTE_TARGET }}/*
            && mv ./build/* ./${{ secrets.REMOTE_TARGET }}
            && rm -rf ./build